import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SideBar from "@/Pages/sideBar";
import AdminBar from "@/Pages/adminBar";
import "./globals.css";

// Chargement des polices avec options correctes
const geistSans = Geist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-sans",
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-mono",
  weight: ["400", "700"],
});

// Métadonnées pour l'application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row gap-7 min-h-screen">
          <SideBar />
          <div className="flex-1">
            <AdminBar />
            <main className="p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
